kind: Namespace
apiVersion: v1
metadata:
  name: ${namespace}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-example-deployment
  namespace: ${namespace}
spec:
  selector:
    matchLabels:
      app: tomcat-example
  replicas: 3
  template:
    metadata:
      labels:
        app: tomcat-example
    spec:
      containers:
        - name: tomcat-example
          # enter the path to your image, be sure to include the correct region prefix
          image: iad.ocir.io/odx-pipelines/js-test/maven-tomcat-example:${BUILDRUN_HASH}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-example-service
  namespace: ${namespace}
  annotations: 
    service.beta.kubernetes.io/oci-load-balancer-shape: "10Mbps"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: tomcat-example
