kind: Namespace
apiVersion: v1
metadata:
  name: ${namespace_canary}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  namespace: ${namespace_canary}
  name: ocr-credentials
stringData:
  .dockerconfigjson: '{"auths":{"$DOCKER_REGISTRY":{"username":"$DOCKER_USERNAME","password":"$DOCKER_AUTH_TOKEN","auth":"base64($DOCKER_USERNAME:$DOCKER_AUTH_TOKEN)"}}}'
---
apiVersion: v1
data:
  .dockerconfigjson: <base 64 of ~/.docker/config.json>
kind: Secret
metadata:
  namespace: ${namespace_canary}
  name: ocr-credentials
type: kubernetes.io/dockerconfigjson
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-example-deployment
  namespace: ${namespace_canary}
spec:
  selector:
    matchLabels:
      app: tomcat-example
  replicas: 3
  template:
    metadata:
      labels:
        app: tomcat-example
    spec:
      containers:
        - name: tomcat-example
          # enter the path to your image, be sure to include the correct region prefix
          image: us-ashburn-1.ocir.io/fahdabidiroottenancy/rahul/mr-devops-canary/tomcat-java:${BUILDRUN_HASH}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
      imagePullSecrets:
        - name: ocr-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-example-service
  namespace: ${namespace_canary}
  annotations: 
    service.beta.kubernetes.io/oci-load-balancer-shape: "10Mbps"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: tomcat-example
